name: Daily RSI Screener

on:
  # Daily schedule at 12:00 UTC
  schedule:
    - cron: '0 12 * * *'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug output'
        required: false
        default: 'false'
        type: boolean
  
  # Run on push to main for testing
  push:
    branches: [ main ]

# Required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run RSI Screener
      run: |
        if [ "${{ github.event.inputs.debug }}" = "true" ]; then
          echo "Debug mode enabled"
          python -v rsi_screener.py
        else
          python rsi_screener.py
        fi
    
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4
    
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs
    
    - name: Display deployment info
      run: |
        echo "📊 RSI Screener completed successfully!"
        echo "📁 Generated files in docs/ directory:"
        ls -la docs/
        echo ""
        echo "🌐 GitHub Pages will be deployed to:"
        echo "   ${{ steps.pages.outputs.base_url }}"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: analyze
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4